"""Spotting failures.

Spot fires are the error channel where "the forecast was slightly wrong" and
"the forecast was catastrophically wrong for this decision" diverge most
sharply: a spot ignition on the far side of a route converts a safe route into
a trap, and no amount of accuracy about the main front compensates.

Three failure modes, matching the three ways a spot prediction can be wrong:

``SpotMiss``
    The forecast omits the spot entirely.  Consumes a **latent uniform**
    ``spot_miss_u`` in ``[0, 1]``; the spot is dropped when
    ``spot_miss_u < p_miss``.  Latent-uniform thresholding (rather than an
    internal Bernoulli draw) is what lets a missed spot be *correlated* with,
    say, a spread-rate bias -- see :mod:`~.combined`.

``SpotDelay``
    The forecast has the spot but too late: ``t0' = t0 + spot_delay``.
    ``spot_delay >= 0`` is enforced.  A negative value would be a forecast
    that predicts an ignition *before* it happens, which is a different
    (clairvoyant) failure and is rejected here rather than quietly allowed.

``SpotDisplacement``
    The forecast has the spot at the wrong place.  Shares the implementation
    of :class:`~.displacement.SpatialDisplacement` with a spot selector and a
    distinct parameter prefix, so spot displacement and main-front
    displacement are separate, separately-correlatable channels.

All three default to selecting ``kind="spot"`` sources only.

A note on what is *not* modelled: spot ignitions here are exogenous properties
of the world, not stochastically generated by the main front.  A forecast
therefore cannot "predict a spot that did not occur" unless the scenario
places a phantom spot in the forecast state explicitly.  False-alarm spotting
is listed in ``docs/SCOPE.md`` as out of scope for v0.1 and in
``docs/FAILURE_MODES.md`` as a known asymmetry in the error model.
"""

from __future__ import annotations

import numpy as np

from wildfireguardian_forecast_value.degradation.base import DegradationOperator, SourceSelector
from wildfireguardian_forecast_value.degradation.displacement import SpatialDisplacement
from wildfireguardian_forecast_value.fields.front import FireSource

__all__ = ["SpotMiss", "SpotDelay", "SpotDisplacement"]


class SpotMiss(DegradationOperator):
    """Drop spot sources with probability ``p_miss``, via a latent uniform."""

    name = "spot_miss"
    param_names = ("spot_miss_u",)

    def __init__(self, p_miss: float = 0.0, selector: SourceSelector | None = None) -> None:
        super().__init__(selector if selector is not None else SourceSelector.spots())
        if not (0.0 <= p_miss <= 1.0):
            raise ValueError(f"p_miss must be in [0, 1], got {p_miss!r}")
        self.p_miss = float(p_miss)

    def identity_params(self) -> dict[str, float]:
        # u = 1.0 never triggers a miss for any p_miss <= 1.
        return {"spot_miss_u": 1.0}

    def _apply_to_source(self, source: FireSource, values) -> FireSource | None:
        u = float(values["spot_miss_u"])
        if not (0.0 <= u <= 1.0):
            raise ValueError(f"spot_miss_u is a latent uniform and must lie in [0, 1], got {u!r}")
        return None if u < self.p_miss else source

    def _config(self) -> dict:
        return {"p_miss": self.p_miss}


class SpotDelay(DegradationOperator):
    """``t0 -> t0 + spot_delay`` on spot sources."""

    name = "spot_delay"
    param_names = ("spot_delay",)

    def __init__(self, selector: SourceSelector | None = None) -> None:
        super().__init__(selector if selector is not None else SourceSelector.spots())

    def identity_params(self) -> dict[str, float]:
        return {"spot_delay": 0.0}

    def _apply_to_source(self, source: FireSource, values) -> FireSource:
        delay = float(values["spot_delay"])
        if not np.isfinite(delay) or delay < 0.0:
            raise ValueError(
                f"spot_delay must be finite and >= 0 (a negative delay is clairvoyance, "
                f"not error); got {delay!r}"
            )
        return source.with_(ignition_time=source.ignition_time + delay)


class SpotDisplacement(SpatialDisplacement):
    """Spatial displacement restricted to spot sources, with its own parameters."""

    name = "spot_displacement"

    def __init__(self, mode: str = "polar", selector: SourceSelector | None = None) -> None:
        super().__init__(
            selector=selector if selector is not None else SourceSelector.spots(),
            mode=mode,
            relative_to_heading=False,
            param_prefix="spot_disp",
        )
